const fs = require('fs');
const path = require('path');

const IMAGE_ROOT = path.join(__dirname, '..', 'Image');
const OUTPUT = path.join(__dirname, '..', 'imageManifest.js');

const IMAGE_EXTS = new Set(['.jpg', '.jpeg', '.png', '.gif', '.webp', '.JPG', '.JPEG', '.PNG', '.GIF', '.WEBP']);
const VIDEO_EXTS = new Set(['.mp4', '.mov', '.webm', '.MP4', '.MOV', '.WEBM']);
const MEDIA_EXTS = new Set([...IMAGE_EXTS, ...VIDEO_EXTS]);

function naturalSort(a, b) {
  return a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' });
}

function listMediaInDir(dir) {
  if (!fs.existsSync(dir)) return [];

  return fs.readdirSync(dir)
    .filter(name => MEDIA_EXTS.has(path.extname(name)))
    .sort(naturalSort);
}

function dedupeWebp(filenames) {
  const names = new Set(filenames);
  return filenames.filter(name => {
    if (!name.toLowerCase().endsWith('.webp')) return true;
    const png = name.replace(/\.webp$/i, '.png');
    return !names.has(png);
  });
}

function scanFolders(dir, relativePath = '') {
  const manifest = {};

  if (relativePath) {
    const images = listMediaInDir(dir);
    if (images.length) {
      manifest[relativePath] = dedupeWebp(images).map(name => `Image/${relativePath}/${name}`);
    }
  }

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const nextPath = relativePath ? `${relativePath}/${entry.name}` : entry.name;
    Object.assign(manifest, scanFolders(path.join(dir, entry.name), nextPath));
  }

  return manifest;
}

const manifest = scanFolders(IMAGE_ROOT);
const output = `// Auto-generated by scripts/generateImageManifest.js — do not edit by hand\nconst imageManifest = ${JSON.stringify(manifest, null, 2)};\n`;

fs.writeFileSync(OUTPUT, output);
console.log(`Wrote ${Object.keys(manifest).length} folders to imageManifest.js`);
